server:
  port: 6401
spring:
  rabbitmq:
    host: localhost
    port: 5432
    username: guest
    password: guest
    virtual-host: /
    listener:
      simple:
        acknowledge-mode: manual
        prefetch: 1
        retry:
          enabled: true
          max-attempts: 2
          initial-interval: 5000
    auction-queue: auction
